# Generated by Django 6.1.1 on 2026-10-04 17:56

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "aggregate",
                    models.CharField(
                        help_text="Entity the event is about, e.g. 'order'.", max_length=100
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="What happened, e.g. 'order.placed'.", max_length=100
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed (attempts exhausted)"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="django_even_status_927b1e_idx"
                    ),
                    models.Index(
                        fields=["aggregate", "-created_at"], name="django_even_aggrega_ec7910_idx"
                    ),
                ],
            },
        ),
    ]
